package qwen

import (
	"encoding/json"
	"fmt"
	"os"

	"agent-bridge/internal/domain"
)

// NormalizeCore parses artifacts generated by Qwen into domain.ResultSpec.
func NormalizeCore(attemptID string, resultPath string) (*domain.ResultSpec, error) {
	if resultPath == "" {
		return nil, fmt.Errorf("no result_json artifact found for attempt %s", attemptID)
	}

	data, err := os.ReadFile(resultPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read Qwen result JSON: %w", err)
	}

	var res domain.ResultSpec
	if err := json.Unmarshal(data, &res); err != nil {
		return nil, fmt.Errorf("failed to unmarshal Qwen result JSON: %w", err)
	}

	if res.State == "" {
		res.State = domain.StepStateFailedTerminal
		res.Summary = "Invalid result: missing status"
	}

	return &res, nil
}
