import type { ActivationCommand } from "@/schemas/activation";
import type { AuditEvent } from "@/schemas/audit";
import type { Connector } from "@/schemas/connectors";
import type { ExecutorProfile } from "@/schemas/executors";
import type { Machine } from "@/schemas/machines";
import type { Project } from "@/schemas/projects";
import type { RelayHealth } from "@/schemas/relay-health";
import type { RelayProfile } from "@/schemas/relays";
import type { RunRecord } from "@/schemas/run-history";
import type { User, Workspace } from "@/schemas/workspace";

type DemoSnapshot = {
  activationCommands: ActivationCommand[];
  auditEvents: AuditEvent[];
  connectors: Connector[];
  executors: ExecutorProfile[];
  machines: Machine[];
  mcpEndpoint: string;
  projects: Project[];
  relayHealth: RelayHealth[];
  relays: RelayProfile[];
  runs: RunRecord[];
  user: User;
  workspace: Workspace;
};

export const demoSnapshot: DemoSnapshot = {
  user: {
    id: "user_demo",
    email: "operator@example.com",
    displayName: "Demo Operator",
  },
  workspace: {
    id: "ws_personal",
    kind: "demo",
    name: "Personal Gateway Workspace",
    slug: "personal",
    mode: "demo",
  },
  mcpEndpoint: "http://127.0.0.1:19090/mcp",
  relays: [
    {
      id: "default",
      name: "Default self-host Relay",
      type: "self_host",
      url: "http://127.0.0.1:8090",
      tokenRef: "CODENCER_DEFAULT_RELAY_TOKEN",
      tokenConfigured: true,
      enabled: true,
      status: "available",
    },
    {
      id: "personal-vps",
      name: "Personal self-host Relay",
      type: "self_host",
      url: "https://relay.example.com",
      tokenRef: "CODENCER_RELAY_PERSONAL_TOKEN",
      tokenConfigured: true,
      enabled: true,
      status: "available",
    },
    {
      id: "lab",
      name: "Lab Relay",
      type: "self_host",
      url: "https://relay-lab.example.com",
      tokenRef: "CODENCER_RELAY_LAB_TOKEN",
      tokenConfigured: true,
      enabled: false,
      status: "disabled",
    },
  ],
  relayHealth: [
    {
      relayProfileId: "default",
      status: "available",
      latencyMs: 42,
      checkedAt: "2026-06-20T12:15:00Z",
    },
    {
      relayProfileId: "personal-vps",
      status: "available",
      latencyMs: 61,
      checkedAt: "2026-06-20T12:15:00Z",
    },
    {
      relayProfileId: "lab",
      status: "disabled",
      latencyMs: null,
      checkedAt: "2026-06-20T12:15:00Z",
    },
  ],
  machines: [
    {
      id: "mach_mac",
      hostname: "macbook.local",
      hostLabel: "macbook",
      os: "darwin",
      arch: "arm64",
      status: "online",
    },
    {
      id: "mach_wsl",
      hostname: "wsl-coder",
      hostLabel: "wsl2",
      os: "linux",
      arch: "amd64",
      status: "offline",
    },
  ],
  connectors: [
    {
      id: "conn_01",
      machineId: "mach_mac",
      relayProfileId: "default",
      label: "macbook connector",
      status: "online",
      lastSeen: "2026-06-20T12:14:58Z",
    },
    {
      id: "conn_02",
      machineId: "mach_wsl",
      relayProfileId: "personal-vps",
      label: "wsl connector",
      status: "offline",
      lastSeen: "2026-06-19T18:03:20Z",
    },
  ],
  executors: [
    {
      id: "claude-default",
      adapter: "claude",
      daemon_adapter: "claude",
      output_format: "json",
      description: "Non-interactive Claude CLI execution.",
    },
    {
      id: "codex-danger-bypass",
      adapter: "codex",
      daemon_adapter: "codex",
      dangerous_bypass_approvals_and_sandbox: true,
      requires_explicit_allow_dangerous_bypass: true,
      description:
        "Maximum bypass mode. Only for isolated machines, VMs, or containers.",
    },
    {
      id: "codex-full",
      adapter: "codex",
      daemon_adapter: "codex",
      approval: "never",
      sandbox: "danger-full-access",
      description:
        "Non-interactive Codex execution with full local access. Requires explicit profile selection.",
    },
    {
      id: "codex-workspace",
      adapter: "codex",
      daemon_adapter: "codex",
      approval: "never",
      sandbox: "workspace-write",
      description:
        "Non-interactive Codex execution with workspace write access.",
    },
    {
      id: "antigravity-default",
      adapter: "antigravity",
      daemon_adapter: "antigravity",
      description:
        "Antigravity execution through the daemon's repo-scoped binding.",
    },
    {
      id: "antigravity-broker",
      adapter: "antigravity",
      daemon_adapter: "antigravity-broker",
      description: "Antigravity execution through the configured broker.",
    },
    {
      id: "fake-blocker",
      adapter: "fake",
      daemon_adapter: "fake-blocker",
      description: "Deterministic test blocker profile.",
    },
    {
      id: "fake-failure",
      adapter: "fake",
      daemon_adapter: "fake-failure",
      description: "Deterministic test terminal failure profile.",
    },
    {
      id: "fake-success",
      adapter: "fake",
      daemon_adapter: "fake-success",
      description: "Deterministic test success profile.",
    },
    {
      id: "fake-timeout",
      adapter: "fake",
      daemon_adapter: "fake-timeout",
      description: "Deterministic test timeout profile.",
    },
  ],
  projects: [
    {
      id: "codencer",
      name: "Codencer",
      adapter: "codex",
      profile: "codex-workspace",
      locations: [
        {
          id: "loc_01",
          projectId: "codencer",
          relayProfileId: "default",
          connectorId: "conn_01",
          machineId: "mach_mac",
          hostLabel: "macbook",
          hostname: "dev-macbook",
          repoLabel: "codencer",
          repoHash: "repo_9f12ac",
          status: "online",
          ambiguity: "none",
        },
        {
          id: "loc_02",
          projectId: "codencer",
          relayProfileId: "personal-vps",
          connectorId: "conn_01",
          machineId: "mach_mac",
          hostLabel: "macbook",
          hostname: "dev-macbook",
          repoLabel: "codencer",
          repoHash: "repo_9f12ac",
          status: "online",
          ambiguity: "relay_profile",
        },
      ],
    },
    {
      id: "docs-site",
      name: "Docs Site",
      adapter: "codex",
      profile: "codex-workspace",
      locations: [
        {
          id: "loc_03",
          projectId: "docs-site",
          relayProfileId: "personal-vps",
          connectorId: "conn_02",
          machineId: "mach_wsl",
          hostLabel: "wsl2",
          hostname: "wsl-coder",
          repoLabel: "docs-site",
          repoHash: "repo_a82bc3",
          status: "offline",
          ambiguity: "machine_location",
        },
      ],
    },
  ],
  auditEvents: [
    {
      id: "evt_run_09",
      type: "report_read",
      summary: "Read run report run_demo_console for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:42Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        run_id: "run_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_run_08",
      type: "report_read",
      summary: "Read run report run_demo_console for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:40Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        run_id: "run_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_run_07",
      type: "run_completed",
      summary: "Run run_demo_console completed for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:35Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        run_id: "run_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_run_06",
      type: "run_started",
      summary: "Started simple task for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:02Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        run_id: "run_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_run_05",
      type: "executor_selected",
      summary: "Selected executor profile codex-workspace for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:01Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_run_04",
      type: "connector_selected",
      summary:
        "Selected connector conn_01 on machine mach_mac for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:01Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
        connector_id: "conn_01",
        machine_id: "mach_mac",
      },
    },
    {
      id: "evt_run_03",
      type: "relay_selected",
      summary: "Selected Relay profile default for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:01Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
        relay_profile_id: "default",
      },
    },
    {
      id: "evt_run_02",
      type: "route_resolved",
      summary: "Resolved project route for codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:01Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_run_01",
      type: "task_submitted",
      summary: "Submitted simple task for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:18:00Z",
      severity: "info",
      runHistoryId: "runhist_demo_console",
      metadata: {
        executor_adapter: "codex",
        run_history_id: "runhist_demo_console",
        project_id: "codencer",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_claude_03",
      type: "report_read",
      summary: "Read run report run_demo_claude for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:20:40Z",
      severity: "info",
      runHistoryId: "runhist_demo_claude",
      metadata: {
        executor_adapter: "claude",
        run_history_id: "runhist_demo_claude",
        run_id: "run_demo_claude",
        project_id: "codencer",
        executor_profile: "claude-default",
      },
    },
    {
      id: "evt_claude_02",
      type: "run_completed",
      summary: "Run run_demo_claude completed for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:20:35Z",
      severity: "info",
      runHistoryId: "runhist_demo_claude",
      metadata: {
        executor_adapter: "claude",
        run_history_id: "runhist_demo_claude",
        run_id: "run_demo_claude",
        project_id: "codencer",
        executor_profile: "claude-default",
      },
    },
    {
      id: "evt_claude_01",
      type: "task_submitted",
      summary: "Submitted simple task for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:20:00Z",
      severity: "info",
      runHistoryId: "runhist_demo_claude",
      metadata: {
        executor_adapter: "claude",
        run_history_id: "runhist_demo_claude",
        project_id: "codencer",
        executor_profile: "claude-default",
      },
    },
    {
      id: "evt_blocked_04",
      type: "human_interrupt_created",
      summary: "Executor needs an operator answer before continuing.",
      actor: "gateway",
      createdAt: "2026-06-20T12:22:20Z",
      severity: "warning",
      runHistoryId: "runhist_demo_blocked",
      metadata: {
        interrupt_type: "clarifying_question_required",
        prompt: "Confirm whether the executor should inspect README only.",
        project_id: "codencer",
        requested_action: "answer_question",
        run_history_id: "runhist_demo_blocked",
        run_id: "run_demo_blocked",
        status: "waiting_for_human",
      },
    },
    {
      id: "evt_blocked_03",
      type: "blocker",
      summary: "Run run_demo_blocked reached a blocker for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:22:18Z",
      severity: "warning",
      runHistoryId: "runhist_demo_blocked",
      metadata: {
        executor_adapter: "codex",
        executor_profile: "codex-workspace",
        project_id: "codencer",
        run_history_id: "runhist_demo_blocked",
        run_id: "run_demo_blocked",
      },
    },
    {
      id: "evt_blocked_02",
      type: "run_started",
      summary: "Started simple task for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:22:01Z",
      severity: "info",
      runHistoryId: "runhist_demo_blocked",
      metadata: {
        executor_adapter: "codex",
        executor_profile: "codex-workspace",
        project_id: "codencer",
        run_history_id: "runhist_demo_blocked",
        run_id: "run_demo_blocked",
      },
    },
    {
      id: "evt_blocked_01",
      type: "task_submitted",
      summary: "Submitted simple task for project codencer",
      actor: "gateway",
      createdAt: "2026-06-20T12:22:00Z",
      severity: "info",
      runHistoryId: "runhist_demo_blocked",
      metadata: {
        executor_adapter: "codex",
        project_id: "codencer",
        run_history_id: "runhist_demo_blocked",
        executor_profile: "codex-workspace",
      },
    },
    {
      id: "evt_01",
      type: "relay.add",
      summary: "Added Personal self-host Relay profile.",
      actor: "operator@example.com",
      createdAt: "2026-06-20T12:10:00Z",
      severity: "info",
    },
    {
      id: "evt_02",
      type: "connector.login",
      summary: "Created connector login binding for macbook.",
      actor: "operator@example.com",
      createdAt: "2026-06-20T12:08:00Z",
      severity: "info",
    },
    {
      id: "evt_03",
      type: "routing.blocker",
      summary: "Project codencer needs relay_profile_id selector.",
      actor: "gateway",
      createdAt: "2026-06-20T12:07:00Z",
      severity: "warning",
    },
  ],
  runs: [
    {
      completedAt: "2026-06-20T12:18:35Z",
      connectorId: "conn_01",
      createdAt: "2026-06-20T12:18:00Z",
      executorAdapter: "codex",
      executorProfile: "codex-workspace",
      executionMode: "real",
      goal: "Inspect the project README and return a short summary. Do not modify files.",
      hostLabel: "macbook",
      id: "runhist_demo_console",
      machineId: "mach_mac",
      mode: "task",
      projectId: "codencer",
      projectName: "Codencer",
      relayProfileId: "default",
      report: {
        status: "completed",
        task: {
          adapter: "codex",
          profile: "codex-workspace",
          status: "completed",
          step_id: "step_demo_console",
          summary:
            "Codencer bridges planners to coding executors through local and self-host services.",
        },
        evidence: {
          artifacts: [
            {
              id: "artifact-demo-stdout",
              name: "stdout.log",
              type: "stdout",
              mime_type: "text/plain",
              size: 220,
            },
          ],
          result: {
            adapter: "codex",
            is_simulation: false,
            raw_output:
              "Codencer is a local/self-host bridge between AI planners and coding executors. It records structured runs, results, blockers, and audit evidence.",
          },
        },
      },
      reportStatus: "completed",
      resultDetails:
        "Codencer is a local/self-host bridge between AI planners and coding executors. It records structured runs, results, blockers, and audit evidence.",
      resultSummary:
        "Codencer bridges planners to coding executors through local and self-host services.",
      runId: "run_demo_console",
      scope: "gateway_submitted",
      startedAt: "2026-06-20T12:18:00Z",
      status: "completed",
      stepId: "step_demo_console",
      title: "Codex workspace smoke task",
      updatedAt: "2026-06-20T12:18:40Z",
    },
    {
      completedAt: "2026-06-20T12:20:35Z",
      connectorId: "conn_01",
      createdAt: "2026-06-20T12:20:00Z",
      executorAdapter: "claude",
      executorProfile: "claude-default",
      executionMode: "real",
      goal: "Inspect the project README and return a short summary. Do not modify files.",
      hostLabel: "macbook",
      id: "runhist_demo_claude",
      machineId: "mach_mac",
      mode: "task",
      projectId: "codencer",
      projectName: "Codencer",
      relayProfileId: "default",
      report: {
        status: "completed",
        task: {
          adapter: "claude",
          profile: "claude-default",
          status: "completed",
          step_id: "step_demo_claude",
          summary:
            "Claude reported that Codencer is a bridge for approved local/self-host executor runs.",
        },
        evidence: {
          artifacts: [
            {
              id: "artifact-demo-claude-stdout",
              name: "stdout.log",
              type: "stdout",
              mime_type: "text/plain",
              size: 180,
            },
            {
              id: "artifact-demo-claude-stdout",
              name: "stdout.log",
              type: "stdout",
              mime_type: "text/plain",
              size: 180,
            },
          ],
          result: {
            adapter: "claude",
            is_simulation: false,
            raw_output:
              "The README presents Codencer as a bridge, not a planner, for local and self-host coding execution.",
          },
        },
      },
      reportStatus: "completed",
      resultDetails:
        "The README presents Codencer as a bridge, not a planner, for local and self-host coding execution.",
      resultSummary:
        "Claude reported Codencer as a bridge for approved executor runs.",
      runId: "run_demo_claude",
      scope: "gateway_submitted",
      startedAt: "2026-06-20T12:20:00Z",
      status: "completed",
      stepId: "step_demo_claude",
      title: "Claude CLI smoke task",
      updatedAt: "2026-06-20T12:20:40Z",
    },
    {
      completedAt: undefined,
      connectorId: "conn_01",
      createdAt: "2026-06-20T12:22:00Z",
      executorAdapter: "codex",
      executorProfile: "codex-workspace",
      executionMode: "unknown",
      goal: "Inspect the project README after operator confirmation.",
      hostLabel: "macbook",
      id: "runhist_demo_blocked",
      machineId: "mach_mac",
      mode: "task",
      projectId: "codencer",
      projectName: "Codencer",
      relayProfileId: "default",
      report: {
        blocker: {
          message: "Executor needs an operator answer before continuing.",
          type: "question",
        },
        run_id: "run_demo_blocked",
        status: "blocked",
      },
      reportStatus: "blocked",
      resultDetails: "Executor needs an operator answer before continuing.",
      resultSummary: "Waiting for an operator answer.",
      runId: "run_demo_blocked",
      scope: "gateway_submitted",
      startedAt: "2026-06-20T12:22:00Z",
      status: "blocked",
      stepId: "step_demo_blocked",
      title: "Codex blocked smoke task",
      updatedAt: "2026-06-20T12:22:20Z",
    },
  ],
  activationCommands: [
    {
      id: "login",
      title: "Log in to Gateway",
      description:
        "Creates a workspace-bound Gateway session under CODENCER_HOME.",
      target: "gateway",
      command: "codencer login --gateway http://127.0.0.1:19090",
    },
    {
      id: "connector-login",
      title: "Bind local connector",
      description:
        "Requests a short-lived Relay enrollment secret through Gateway; output is redacted.",
      target: "gateway",
      command:
        "codencer connector login --gateway http://127.0.0.1:19090 --relay default --json",
    },
    {
      id: "project-init",
      title: "Create project config",
      description:
        "Commits only .codencer/project.json; local state stays in CODENCER_HOME.",
      target: "local",
      command:
        "codencer project init --id codencer --repo . --adapter codex --profile codex-workspace --json",
    },
    {
      id: "project-share",
      title: "Share project explicitly",
      description: "Connector advertises this project to the selected Relay.",
      target: "local",
      command: "codencer project share codencer --json",
    },
    {
      id: "codex",
      title: "Codex MCP setup",
      description: "AI clients point to Gateway, not a user Relay.",
      target: "client",
      command:
        "codencer setup mcp --client codex --endpoint http://127.0.0.1:19090/mcp --json",
    },
    {
      id: "claude",
      title: "Claude Code MCP setup",
      description: "Generates the Gateway MCP command for Claude Code.",
      target: "client",
      command:
        "codencer setup mcp --client claude-code --endpoint http://127.0.0.1:19090/mcp --json",
    },
    {
      id: "chatgpt",
      title: "ChatGPT custom MCP setup",
      description: "Uses Gateway OAuth dev metadata for controlled testing.",
      target: "client",
      command:
        "codencer activation self-host --gateway http://127.0.0.1:19090 --project codencer --token-env CODENCER_GATEWAY_MCP_TOKEN --json",
    },
    {
      id: "curl",
      title: "Gateway curl smoke",
      description: "Runs MCP initialize/tools/list against Gateway.",
      target: "gateway",
      command:
        "curl -fsS http://127.0.0.1:19090/mcp -H 'Authorization: Bearer $CODENCER_GATEWAY_MCP_TOKEN'",
    },
  ],
};
