"use client";

import { ActivationCommandPanel } from "@/components/console/activation-command-panel";
import {
  DemoModeNotice,
  OfficialGatewayNotice,
} from "@/components/console/mode-notices";
import { PageShell } from "@/components/layout/page-shell";
import { Alert } from "@/components/ui/alert";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingPanel } from "@/components/ui/skeleton";
import { isDemoMode } from "@/api/config";
import { useActivationCommands } from "@/api/activation";
import { useWorkspace } from "@/api/workspace";

export function ActivationScreen() {
  const activation = useActivationCommands();
  const workspace = useWorkspace();
  return (
    <PageShell
      breadcrumbs={[
        { label: "Console", href: "/console" },
        { label: "Activation" },
      ]}
      description="Copy safe Gateway-first commands for CLI login, connector binding, project sharing, MCP setup, and smoke checks."
      kicker="Activation"
      title="Gateway-first setup"
    >
      {activation.isLoading ? <LoadingPanel /> : null}
      {workspace.isLoading ? <LoadingPanel /> : null}
      {activation.error ? (
        <Alert title="Activation API unavailable" tone="danger">
          {activation.error.message}
        </Alert>
      ) : null}
      {workspace.error ? (
        <Alert title="Workspace API unavailable" tone="danger">
          {workspace.error.message}
        </Alert>
      ) : null}
      {activation.data && workspace.data ? (
        <div className="grid min-w-0 max-w-full gap-lg">
          {isDemoMode() ? <DemoModeNotice /> : null}
          <OfficialGatewayNotice mcpEndpoint={workspace.data.mcpEndpoint} />
          {activation.data.activationCommands.length === 0 ? (
            <EmptyState
              description="Activation commands are generated by Gateway."
              title="No activation commands"
            />
          ) : (
            <ActivationCommandPanel
              commands={activation.data.activationCommands}
            />
          )}
        </div>
      ) : null}
    </PageShell>
  );
}
