package claude

import (
	"encoding/json"
	"fmt"
	"os"

	"agent-bridge/internal/domain"
)

// NormalizeCore parses artifacts generated by Claude into domain.Result.
func NormalizeCore(attemptID string, resultPath string) (*domain.Result, error) {
	if resultPath == "" {
		return nil, fmt.Errorf("no result_json artifact found for attempt %s", attemptID)
	}

	data, err := os.ReadFile(resultPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read Claude result JSON: %w", err)
	}

	var res domain.Result
	if err := json.Unmarshal(data, &res); err != nil {
		return nil, fmt.Errorf("failed to unmarshal Claude result JSON: %w", err)
	}

	if res.Status == "" {
		res.Status = domain.StepStateFailedTerminal
		res.Summary = "Invalid result: missing status"
	}

	return &res, nil
}
