package codex

import (
	"encoding/json"
	"fmt"
	"os"

	"agent-bridge/internal/domain"
)

// NormalizeCore parses the artifacts generated by Codex into a standard domain.ResultSpec.
func NormalizeCore(attemptID string, resultPath string, adapterName string, isSimulation bool) (*domain.ResultSpec, error) {
	defaultRes := &domain.ResultSpec{
		AttemptID:    attemptID,
		Adapter:      adapterName,
		IsSimulation: isSimulation,
	}

	if resultPath == "" {
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = "Bridge Interface Error: Codex agent finished but failed to produce result.json artifact."
		return defaultRes, nil
	}

	data, err := os.ReadFile(resultPath)
	if err != nil {
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = fmt.Sprintf("Bridge Interface Error: Failed to read Codex result.json: %v", err)
		return defaultRes, nil
	}

	var res domain.ResultSpec
	if err := json.Unmarshal(data, &res); err != nil {
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = fmt.Sprintf("Bridge Interface Error: Codex returned malformed result.json: %v", err)
		return defaultRes, nil
	}

	// Ensure metadata is correctly set/overridden
	res.AttemptID = attemptID
	res.Adapter = adapterName
	res.IsSimulation = isSimulation

	// Sanity check state
	if res.State == "" {
		res.State = domain.StepStateFailedTerminal
		res.Summary = "Bridge Interface Error: Codex result spec missing 'state' field."
	}

	return &res, nil
}
