package codex

import (
	"encoding/json"
	"fmt"
	"os"

	"agent-bridge/internal/domain"
)

// NormalizeCore parses the artifacts generated by Codex into a standard domain.ResultSpec.
func NormalizeCore(attemptID string, artifacts []*domain.Artifact, adapterName string, isSimulation bool) (*domain.ResultSpec, error) {
	defaultRes := &domain.ResultSpec{
		AttemptID:    attemptID,
		Adapter:      adapterName,
		IsSimulation: isSimulation,
	}

	var resultPath string
	for _, art := range artifacts {
		switch art.Type {
		case domain.ArtifactTypeResultJSON:
			resultPath = art.Path
		}
	}

	if resultPath == "" {
		if isSimulation {
			defaultRes.State = domain.StepStateCompleted
			defaultRes.Summary = "Simulation: Codex agent relay completed successfully (Mock result)."
			return defaultRes, nil
		}
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = "Bridge Interface Error: Codex agent finished but failed to produce result.json artifact."
		return defaultRes, nil
	}

	// Verify file existence and get metadata
	info, err := os.Stat(resultPath)
	if err != nil {
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = fmt.Sprintf("Bridge Interface Error: Failed to access Codex result.json: %v", err)
		return defaultRes, nil
	}

	data, err := os.ReadFile(resultPath)
	if err != nil {
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = fmt.Sprintf("Bridge Interface Error: Failed to read Codex result.json: %v", err)
		return defaultRes, nil
	}

	var res domain.ResultSpec
	if err := json.Unmarshal(data, &res); err != nil {
		defaultRes.State = domain.StepStateFailedTerminal
		defaultRes.Summary = fmt.Sprintf("Bridge Interface Error: Codex returned malformed result.json: %v", err)
		return defaultRes, nil
	}

	// Ensure metadata is correctly set/overridden
	res.Version = "v1"
	res.AttemptID = attemptID
	res.Adapter = adapterName
	res.IsSimulation = isSimulation
	res.UpdatedAt = info.ModTime()
	
	if res.Artifacts == nil {
		res.Artifacts = make(map[string]string)
	}
	
	for _, art := range artifacts {
		res.Artifacts[art.Name] = art.Path
		if art.Type == domain.ArtifactTypeStdout {
			res.RawOutputRef = art.Path
		}
	}

	// Sanity check state
	if res.State == "" {
		res.State = domain.StepStateFailedTerminal
		res.Summary = "Bridge Interface Error: Codex result spec missing 'state' field."
	}

	return &res, nil
}
