package codex

import (
	"encoding/json"
	"fmt"
	"os"

	"agent-bridge/internal/domain"
)

// NormalizeCore parses the artifacts generated by Codex into a standard domain.Result.
func NormalizeCore(attemptID string, resultPath string) (*domain.Result, error) {
	if resultPath == "" {
		return nil, fmt.Errorf("no result_json artifact found for attempt %s", attemptID)
	}

	data, err := os.ReadFile(resultPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read result JSON: %w", err)
	}

	var res domain.Result
	if err := json.Unmarshal(data, &res); err != nil {
		return nil, fmt.Errorf("failed to unmarshal result JSON: %w", err)
	}

	// Validate status
	if res.State == "" {
		res.State = domain.StepStateFailedTerminal
		res.Summary = "Invalid result: missing status"
	}

	return &res, nil
}
